# Generated by Django 6.0.3 on 2026-03-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutenticarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol_id',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Aprendiz'), (3, 'orientador')], default=2),
        ),
    ]
