# Generated by Django 6.0.3 on 2026-03-27 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('aprendiz', models.ForeignKey(db_column='id_aprendiz', on_delete=django.db.models.deletion.CASCADE, related_name='citas_aprendiz', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(db_column='id_orientador', on_delete=django.db.models.deletion.CASCADE, related_name='citas_orientador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
