# Generated by Django 6.0.3 on 2026-03-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionarCitasApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='updated_at',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='fecha_cita',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='hora_cita',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='aprendiz',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='motivo_cancelacion',
        ),
        migrations.AddField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(default=1, help_text='Usuario con rol Aprendiz (rol_id=2)', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_estudiante', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_reprogramada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_reprogramada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_reprogramacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('REPROGRAMADA', 'Reprogramada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cita',
            name='orientador',
            field=models.ForeignKey(help_text='Usuario con rol Instructor/Psicosocial (rol_id=3)', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_orientador', to=settings.AUTH_USER_MODEL),
        ),
    ]
