# Generated by Django 6.0.3 on 2026-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionarCitasApp', '0002_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cita',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', help_text='Prioridad estimada según el motivo', max_length=5),
        ),
    ]
