# Generated by Django 6.0.3 on 2026-04-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionarCitasApp', '0003_cita_motivo_cancelacion_cita_prioridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('puntuacion_estres', models.PositiveSmallIntegerField(default=0, help_text='Nivel de estrés evaluado (0-100)')),
                ('puntuacion_ansiedad', models.PositiveSmallIntegerField(default=0, help_text='Nivel de ansiedad evaluado (0-100)')),
                ('nivel_detectado', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=10)),
                ('avance_observado', models.TextField(blank=True, default='', help_text='Descripción del avance del aprendiz en esta cita')),
                ('recomendaciones', models.TextField(blank=True, default='', help_text='Recomendaciones del orientador para el aprendiz')),
                ('observaciones', models.TextField(blank=True, default='', help_text='Notas internas del orientador')),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Marcar si el aprendiz necesita seguimiento especial')),
                ('asistio', models.BooleanField(default=True, help_text='El aprendiz asistió a la cita')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(help_text='Debe ser una cita con estado FINALIZADA', on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='GestionarCitasApp.cita')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_como_orientador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
