# Generated by Django 6.0.3 on 2026-03-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='', max_length=400)),
                ('url_recurso', models.URLField(blank=True, default='', max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Orientador que creó el recurso (rol_id=3)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ActividadAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='', max_length=500)),
                ('url_actividad', models.URLField(blank=True, default='', max_length=300)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada')], default='Pendiente', max_length=15)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(help_text='Aprendiz destinatario (rol_id=2)', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('orientador', models.ForeignKey(help_text='Orientador que asigna (rol_id=3)', on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_como_orientador', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(blank=True, help_text='Recurso base (opcional — puede ser personalizada)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_generadas', to='ActividadApp.recurso')),
            ],
            options={
                'verbose_name': 'Actividad Asignada',
                'verbose_name_plural': 'Actividades Asignadas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
