# Generated by Django 6.0.3 on 2026-03-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActividadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
